spring.application.name=SIT_EVENT
server.port=${PORT}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${URI_ISSUER}
TOKEN_URL=${URL_TOKEN}
CLIENT_ID=${ID_CLIENT}
CLIENT_SECRET=${SECRET_CLIENT}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
